linters:
  enable-all: true
  disable:
  # deprecated linters
    - golint
    - scopelint
    - maligned
    - interfacer
  # disabled linters
    - wsl
    - nlreturn
    - gochecknoglobals
    - paralleltest
    - exhaustivestruct

issues:
  exclude-use-default: false
  exclude:
    - "^G103:"
